package git

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"
	"strings"

	"github.com/malamsyah/leakfix/internal/plan"
)

// BranchName produces the deterministic branch name (SPEC §13.1):
// leakfix/remediate-<short-hash> where <short-hash> is sha256(sorted FindingIDs)[:8].
func BranchName(p *plan.Plan) string {
	ids := make([]string, 0, len(p.Items))
	for _, it := range p.Items {
		ids = append(ids, it.FindingID)
	}
	sort.Strings(ids)
	sum := sha256.Sum256([]byte(strings.Join(ids, "|")))
	return "leakfix/remediate-" + hex.EncodeToString(sum[:])[:8]
}

// PlanHash returns the same short hash for embedding in commit messages.
func PlanHash(p *plan.Plan) string {
	bn := BranchName(p)
	return strings.TrimPrefix(bn, "leakfix/remediate-")
}

// BuildCommitMessage renders the conventional-commit-style message (SPEC §13.2).
// The redacted plan is the only safe input — it never contains literal secrets.
func BuildCommitMessage(p *plan.Plan, issueNumber int) string {
	var b strings.Builder
	b.WriteString("fix(security): replace leaked secrets with env var references\n\n")
	b.WriteString(fmt.Sprintf("Generated by leakfix. Addresses %d secret leak(s) detected by Kingfisher:\n\n", len(p.Items)))
	for _, it := range p.Items {
		file := ""
		if len(it.Locations) > 0 {
			file = it.Locations[0].File
		}
		b.WriteString(fmt.Sprintf("- %s in %s\n", it.DisplayName, file))
	}
	if issueNumber > 0 {
		b.WriteString(fmt.Sprintf("\nTracking issue: #%d\n", issueNumber))
	}
	b.WriteString(fmt.Sprintf("Plan: %s\n", PlanHash(p)))
	b.WriteString(fmt.Sprintf("\n🤖 Generated by leakfix v%s\n", "v1"))
	return b.String()
}

// RedactString applies the same placeholder algorithm used in plan/redact, in
// case any caller (e.g., commit-message builder) wants a defense-in-depth pass.
func RedactString(s string, secrets []string) string {
	return plan.Redact(s, secrets)
}
